# CI.yaml ---
---

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - snapshot

    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install Cask
      uses: conao3/setup-cask@master
      with:
        version: 'snapshot'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Byte Compile
      run: make compile

    - name: Run Tests
      run: make test
